opensquare-network/dotreasury

packages/scan/src/events/treasury/tip.js
packages/scan/src/extrinsic/extractBusiness.js
packages/scan/src/extrinsic/treasury/tip.js

Watch "tip" calls

---

packages/scan/src/events/treasury/bounty.js
packages/scan/src/events/treasury/proposal.js
packages/scan/src/events/treasury/tip.js
packages/scan/src/extrinsic/extractBusiness.js
packages/scan/src/extrinsic/treasury/bounty.js
packages/scan/src/extrinsic/treasury/proposal.js
packages/scan/src/mongo/index.js
packages/scan/src/rollback/index.js

Bounty and proposal

---

packages/scan/src/chain/latestHead.js
packages/scan/src/clean/index.js
packages/scan/src/index.js

We don't have to care the block rollback following the finalized
blocks.

Follow the finalized block

---

packages/scan/src/store/tip.js
packages/server/src/features/tips/routes.js
packages/server/src/features/tips/tips.controller.js

Add tip detail api

---

packages/site/src/App/index.js
packages/site/src/pages/Bounties/index.js
packages/site/src/pages/Header/SubHeader.js
packages/site/src/pages/Overview/index.js
packages/site/src/pages/Proposals/index.js

Fix tab button

---

packages/server/src/features/tips/routes.js
packages/server/src/features/tips/tips.controller.js
packages/site/src/pages/Header/SubHeader.js
packages/site/src/pages/Header/TipsMenu.js
packages/site/src/services/api.js
packages/site/src/services/scanApi.js
packages/site/src/store/reducers/tipSlice.js

Fix tips count

---

packages/site/src/components/ExplorerLink.js
packages/site/src/components/User/Index.js
packages/site/src/services/scanApi.js

Link user to subscan

---

packages/site/src/components/ResponsivePagination.js
packages/site/src/pages/Tips/index.js

Make pagination responsive

---

packages/site/src/constants/index.js
packages/site/src/pages/Tips/TipsTable.js

Show "--" as value for the retracted tips

---

packages/site/src/components/Pagination.js

Pagination style

---

packages/site/src/pages/Header/MainHeader.js

Nav logo to home

---

packages/server/src/features/tips/tips.controller.js
packages/site/src/pages/TipDetail/InformationTable.js
packages/site/src/pages/TipDetail/index.js

Update timeline to show real content

---

packages/site/src/components/ExplorerLink.js
packages/site/src/pages/Timeline/ButtonList.js
packages/site/src/pages/Timeline/Item.js

Update timeline extrinsic link buttons

---

packages/site/src/components/User/Badge.js
packages/site/src/components/User/Index.js
packages/site/src/utils/hooks.js

Fix username fetch

---

packages/site/src/components/TextArea.js
packages/site/src/pages/Comment/Input.js
packages/site/src/pages/TipDetail/InformationTable.js
packages/site/src/pages/TipDetail/PolygonLabel.js
packages/site/src/pages/TipDetail/TipLifeCycleTable.js
packages/site/src/pages/TipDetail/TippersProgress.js

Fix problems on tip detail

---

packages/site/src/pages/Header/ProposalsMenu.js
packages/site/src/pages/Header/SubHeader.js
packages/site/src/pages/Proposals/ProposalsTable.js
packages/site/src/pages/Proposals/index.js
packages/site/src/store/reducers/index.js
packages/site/src/store/reducers/proposalSlice.js

Implement proposal list page

---

packages/server/src/features/proposals/proposals.controller.js
packages/server/src/features/proposals/routes.js
packages/site/src/App/index.js
packages/site/src/constants/index.js
packages/site/src/pages/ProposalDetail/InformationTable.js
packages/site/src/pages/ProposalDetail/PolygonLabel.js
packages/site/src/pages/ProposalDetail/ProposalLifeCycleTable.js
packages/site/src/pages/ProposalDetail/TimeLabel.js
packages/site/src/pages/ProposalDetail/index.js
packages/site/src/store/reducers/proposalSlice.js

Sample proposal detail page

---

packages/scan/src/events/council/index.js

Update proposal state by motion events

---

packages/site/src/components/ExplorerLink.js
packages/site/src/components/ExternalLink.js
packages/site/src/pages/ProposalDetail/index.js
packages/site/src/pages/Timeline/ButtonList.js
packages/site/src/pages/Timeline/FoldableItem.js
packages/site/src/pages/Timeline/index.js
packages/site/src/pages/TipDetail/index.js
packages/site/src/services/polkassembly.js

Link motion to polkassembly

---

packages/scan/src/events/index.js
packages/scan/src/events/treasury/tip.js
packages/scan/src/extrinsic/treasury/tip.js
packages/scan/src/store/tip.js
packages/scan/src/store/utils.js
packages/scan/src/utils/call.js

Normalize tip timeline

---

packages/site/src/pages/TipDetail/index.js

Remove get call

---

packages/scan/src/events/index.js
packages/scan/src/events/treasury/burnt.js
packages/scan/src/mongo/index.js
packages/scan/src/store/burnt.js
packages/scan/src/utils/constants.js

Scan burnt event

---

packages/server/src/features/proposals/proposals.controller.js
packages/site/src/pages/ProposalDetail/index.js
packages/site/src/pages/Timeline/ButtonList.js
packages/site/src/pages/Timeline/Item.js
packages/site/src/utils/index.js

Add awarded to timeline

---

packages/server/src/features/burnt/burnt.controller.js
packages/server/src/features/burnt/routes.js
packages/server/src/mongo/index.js
packages/server/src/routes.js

Add burnt api

---

packages/site/src/App/index.js
packages/site/src/pages/Burnt/BurntTable.js
packages/site/src/pages/Burnt/index.js
packages/site/src/pages/Header/BurntMenu.js
packages/site/src/pages/Header/SubHeader.js
packages/site/src/store/reducers/burntSlice.js
packages/site/src/store/reducers/index.js

Add burnt page

---

packages/server/src/features/bounties/bounties.controller.js
packages/server/src/mongo/index.js
packages/server/src/routes.js
packages/site/src/pages/Bounties/BountiesTable.js

Update bounty list page

---

packages/server/src/features/bounties/bounties.controller.js
packages/site/src/components/Proposer.js
packages/site/src/components/Voter.js
packages/site/src/pages/Bounties/BountiesTable.js
packages/site/src/pages/BountyDetail/BountyLifeCycleTable.js
packages/site/src/pages/BountyDetail/InformationTable.js
packages/site/src/pages/BountyDetail/index.js
packages/site/src/pages/ProposalDetail/index.js

Bind bounty detail data

---

packages/server/src/features/bounties/bounties.controller.js
packages/site/src/pages/Bounties/index.js
packages/site/src/pages/BountyDetail/BountyLifeCycleTable.js
packages/site/src/pages/BountyDetail/InformationTable.js
packages/site/src/pages/BountyDetail/index.js

Update bounty timeline

---

packages/server/src/features/bounties/bounties.controller.js
packages/site/src/components/Label.js
packages/site/src/components/TimeLabel.js
packages/site/src/pages/Bounties/BountiesTable.js
packages/site/src/pages/BountyDetail/BountyLifeCycleTable.js

Fix updata due

---

packages/server/src/services/link.services.js
packages/site/src/pages/TipDetail/InformationTable.js

Fix delete inReason links is not allow

---

packages/site/src/components/Proposer.js
packages/site/src/pages/BountyDetail/index.js
packages/site/src/utils/index.js

Add args for some motions(bounty related)

---

packages/site/src/pages/Overview/BeneficiaryTable.js
packages/site/src/pages/Overview/ProposerTable.js
packages/site/src/pages/Overview/Summary.js
packages/site/src/store/reducers/overviewSlice.js

Bind overview page data

---

packages/site/src/pages/Proposals/Summary.js
packages/site/src/store/reducers/proposalSlice.js

Improve proposal header

---

packages/site/src/components/RelatedLinks.js
packages/site/src/pages/ProposalDetail/InformationTable.js
packages/site/src/pages/ProposalDetail/ProposalLifeCycleTable.js
packages/site/src/pages/Proposals/ProposalsTable.js
packages/site/src/services/polkassembly.js

Add proposal link to life cycle panel

---

packages/server/src/websocket/overview.js
packages/site/src/components/Doughnut.js
packages/site/src/constants/index.js
packages/site/src/pages/Header/BurntMenu.js
packages/site/src/pages/Overview/DoughnutCard.js
packages/site/src/pages/Overview/index.js
packages/site/src/store/reducers/overviewSlice.js

Burn overview

---

packages/server/src/features/auth/auth.controller.js
packages/site/src/pages/Login/index.js
packages/site/src/services/scanApi.js

Support login with email

---

packages/site/src/App/index.js
packages/site/src/pages/Header/index.js
packages/site/src/pages/VerifyEmail/index.js

Add verify page

---

packages/site/src/pages/Comment/Pagination.js
packages/site/src/pages/Comment/ResponsivePagination.js
packages/site/src/pages/Comment/index.js

Update comment pagination style

---

packages/site/src/components/Markdown.js
packages/site/src/pages/Comment/CommentItem.js
packages/site/src/pages/Comment/CommentList.js
packages/site/src/pages/Comment/Input.js
packages/site/src/pages/Comment/index.js

Fix username link

---

packages/site/src/pages/UserSetting/DeleteAccount.js

Go home after account deleted

---

packages/site/src/pages/Toast/index.js

Fix toast position to fixed

---

packages/site/src/components/AccountItem.js
packages/site/src/components/User/index.js
packages/site/src/pages/Header/UserLogin.js
packages/site/src/services/chainApi.js

Update kusama address

---

packages/site/src/App/index.js
packages/site/src/utils/hooks.js

Add preload

---

packages/site/src/pages/Register/index.js
packages/site/src/pages/UserSetting/LinkedAddresses.js

Add link address and sign up success message

---

packages/site/src/App/index.js
packages/site/src/pages/Header/ElectionPhragmenSlashMenu.js
packages/site/src/pages/Header/InflationMenu.js
packages/site/src/pages/Header/MainHeader.js
packages/site/src/pages/Header/SubHeader.js
packages/site/src/utils/hooks.js

Income route

---

packages/site/src/pages/Overview/CustomLabel.js

Fix label child value

---

README.md

Refs #469, add how-to to readme

---

packages/site/public/imgs/caret-right.svg
packages/site/src/pages/Overview/DoughnutCard.js
packages/site/src/pages/Overview/Income.js

Add income link

---

packages/site/src/pages/Comment/Input.js

Refs #460, load latest account verification status

---

packages/site/src/pages/Header/SubHeader.js
packages/site/src/pages/Overview/Income.js
packages/site/src/pages/Overview/TotalStacked/index.js

Refs #481, reorder slash types

---

packages/site/src/pages/Overview/TotalStacked/Chart.js
packages/site/src/pages/Overview/TotalStacked/index.js

Add total stacked treasury

---

packages/site/src/pages/Header/MainHeader.js

optimize menu style for small screen

---

packages/server/src/features/bounties/bounties.controller.js
packages/server/src/features/proposals/proposals.controller.js
packages/server/src/features/tips/tips.controller.js
packages/server/src/migration/db-upgrade/links.multichain.upgrade.js
packages/server/src/migration/index.js
packages/server/src/mongo-admin/index.js
packages/server/src/services/comment.service.js
packages/server/src/services/link.service.js
packages/site/package.json
packages/site/src/pages/BountyDetail/index.js
packages/site/src/pages/ProposalDetail/index.js
packages/site/src/pages/TipDetail/index.js
packages/site/src/store/reducers/commentSlice.js
packages/site/src/store/reducers/linkSlice.js

Multi chains

---

packages/site/src/utils/useUpdateNodesDelay.js

Refs #510, catch api error

---

packages/site/.env.example
packages/site/src/pages/Comment/index.js
packages/site/src/store/reducers/commentSlice.js

Show loading icon before the comments get from the server

---

packages/server/src/features/proposals/proposals.controller.js
packages/server/src/features/tips/tips.controller.js
packages/site/src/components/Select.js
packages/site/src/constants/index.js
packages/site/src/pages/Proposals/Filter.js
packages/site/src/pages/Proposals/index.js
packages/site/src/pages/Tips/Filter.js
packages/site/src/pages/Tips/index.js
packages/site/src/store/reducers/proposalSlice.js
packages/site/src/store/reducers/tipSlice.js

add filter to proposals and tips list page

---

packages/site/src/pages/Login/index.js
packages/site/src/pages/Register/index.js

Disable the button when signup or login is in process #516

---

packages/site/src/pages/Comment/Input.js

Switch the input mode to edit mode when comment button cliecked

---

packages/site/src/pages/Comment/NoComment.js
packages/site/src/pages/Comment/index.js

show better tips when no comments

show better tips when no comments

---

packages/site/src/pages/Bounties/index.js
packages/site/src/pages/Burnt/index.js
packages/site/src/pages/DemocracySlash/index.js
packages/site/src/pages/ElectionPhragmenSlash/index.js
packages/site/src/pages/IdentitySlash/index.js
packages/site/src/pages/Inflation/index.js
packages/site/src/pages/OthersIncome/index.js
packages/site/src/pages/Projects/index.js
packages/site/src/pages/Proposals/index.js
packages/site/src/pages/StakingSlash/index.js
packages/site/src/pages/Tips/index.js
packages/site/src/pages/Transfers/index.js
packages/site/src/pages/TransfersSlash/index.js
packages/site/src/pages/TreasurySlash/index.js
packages/site/src/utils/hooks.js

Ref #638 , add page size storage

Add page size storage

---

packages/server/src/templates/email_verification.hbs

Fix github warning

---

packages/site/src/pages/Bounties/BountiesTable.js

display voting process for bounties (Voting status)

---

packages/site/src/pages/Header/ScanHeight.js

improve header block height display #803

---

packages/site/src/pages/Header/ScanHeight.js

hotfix: header block height & menu button spacing under mobile view

---

packages/site/src/pages/Header/ScanHeight.js

https://user-images.githubusercontent.com/12393771/151689137-963d3395-e388-4d09-ac40-1d5d9a2d69da.mov

hotfix: move ref to the right element

---

yarn.lock

dep: update moment.js to 2.29.2 to prevent injection

---

packages/site/src/components/PolygonLabel.js
packages/site/src/pages/Bounties/BountiesTable.js
packages/site/src/pages/Bounties/ChildBountiesTable.js
packages/site/src/pages/Bounties/index.js
packages/site/src/store/reducers/bountySlice.js

feat: bounties child bounties

---

packages/site/public/imgs/add.svg
packages/site/public/imgs/subtract.svg
packages/site/src/components/TextAccessory.js
packages/site/src/pages/Bounties/BountiesTable.js
packages/site/src/pages/Bounties/index.js
packages/site/src/pages/Bounties/utils.js

feat(site): bounties expand child bounties

---

packages/site/src/pages/Bounties/BountiesTable.js
packages/site/src/pages/BountyDetail/ChildBountiesTable.js
packages/site/src/pages/BountyDetail/index.js
packages/site/src/store/reducers/bountySlice.js

feat(site): bounties detail child bounties

---

packages/site/src/pages/Bounties/BountiesTable.js
packages/site/src/pages/Bounties/index.js

fix(site): bounties misc

---

packages/site/src/pages/Bounties/BountiesTable.js

feat(site): child bounties shows parent index

---

packages/site/src/App/index.js
packages/site/src/pages/Bounties/BountiesTable.js
packages/site/src/pages/Bounties/index.js

feat(site): child bounties route

---

packages/site/src/pages/BountyDetail/ChildBountyDetail/BountyLifeCycleTable.js

bugfix: child bounty create time field & remove update due field

---

packages/site/src/pages/Comment/index.js

HOTFIX: fix comments fetching when index=0

---

packages/site/src/pages/Header/SubHeader.js

hotfix(site): tabber underline

---

packages/site/src/components/TableLoading.js
packages/site/src/pages/ProposalDetail/ProposalLifeCycleTable.js

hotfix: improve syntax to aovid error form browser console

---

packages/site/src/components/Table.js
packages/site/src/components/shared/useTableColumns.js
packages/site/src/pages/Bounties/BountiesTable.js
packages/site/src/pages/Bounties/columns.js
packages/site/src/pages/ChildBounties/ChildBountiesTable.js
packages/site/src/pages/Proposals/ProposalsTable.js

feat: bounties table column curator/beneficiary

---

packages/site/src/components/User/Username.js
packages/site/src/components/User/index.js

hotfix: curator text overflow ellipsis

---

packages/site/src/pages/Bounties/columns.js
packages/site/src/pages/ChildBounties/ChildBountiesTable.js

fix: child bounty table default to beneficiary

---

packages/site/src/pages/UsersDetail/UserInfo.js

fix: page users detail proposals counts loading effect

---

packages/site/src/pages/UsersDetail/ProposalsTables/ProposalsTable.js
packages/site/src/pages/UsersDetail/ProposalsTables/TipsTable.js
packages/site/src/pages/UsersDetail/ProposalsTables/index.js

fix: page users detail temporary disable filter

---

packages/site/src/components/ConnectWallet/loading.svg

fix: connect wallet loading svg

---

packages/site/src/pages/UsersDetail/Councilor/CouncilorShip/index.js

feat: councilor ship height to subscan

---

packages/site/src/components/User/index.js
packages/site/src/components/Voter.js
packages/site/src/pages/Overview/BeneficiaryTable.js
packages/site/src/pages/Overview/ProposerTable.js
packages/site/src/pages/ProposalBeneficiaries/ProposalBeneficiariesTable.js
packages/site/src/pages/ProposalDetail/InformationTable.js
packages/site/src/pages/ProposalDetail/timeline/index.js
packages/site/src/pages/TipFinders/TipFindersTable.js
packages/site/src/utils/url.js

feat: nav to user detail with role

---

packages/site/src/components/Tooltip/utils.js

fix: tooltip force placement

---

packages/site/package.json

https://github.com/opensquare-network/common/issues/5
close #964 , close #927

build: ignore annoying sourcemap warning

---

packages/site/src/GlobalStyle.js
packages/site/src/pages/Header/SlashMenu/PopupMenu.js
packages/site/src/pages/Header/SlashMenu/styled.js

Fix: popup menu style

---

packages/site/public/imgs/caret-up-right.svg
packages/site/src/components/ExternalLink.js
packages/site/src/pages/Overview/DoughnutCardLinkTitle.js
packages/site/src/pages/Overview/Income.js
packages/site/src/pages/Overview/Output.js

feat: home overview doughnut title link

---

packages/site/package.json
packages/site/src/components/BlocksTimeDefaultUnit.js
packages/site/src/components/ConnectWallet/User.js
packages/site/src/components/ConnectWallet/WalletSelect.js
packages/site/src/components/Maintenance.js
packages/site/src/pages/Bounties/NewBountyModal/index.js
packages/site/src/pages/BountyDetail/BountyLifeCycleTable.js
packages/site/src/pages/BountyDetail/ClaimButtonBase.js
packages/site/src/pages/BountyDetail/NewChildBountyModal/index.js
packages/site/src/pages/Comment/CommentItem.js
packages/site/src/pages/Header/ScanHeight.js
packages/site/src/pages/ProposalDetail/ProposalLifeCycleTable.js
packages/site/src/pages/ProposalDetail/timeline/referendum.js
packages/site/src/pages/Proposals/NewProposalModal/index.js
packages/site/src/pages/Timeline/ButtonList.js
packages/site/src/pages/Timeline/FoldableItem.js
packages/site/src/pages/TipDetail/Actions/CloseButton.js
packages/site/src/pages/TipDetail/Actions/EndorseModal/index.js
packages/site/src/pages/TipDetail/Actions/RetractButton.js
packages/site/src/pages/TipDetail/TipLifeCycleTable.js
packages/site/src/pages/Tips/EndorseTipsModal/index.js
packages/site/src/pages/Tips/EndorseTipsModal/useTipsTable.js
packages/site/src/pages/Tips/NewTipModal/index.js
packages/site/src/pages/Toast/ToastItem.js
packages/site/src/pages/UserSetting/Email.js
packages/site/src/pages/UserSetting/LinkedAddresses.js
packages/site/src/pages/VerifyEmail/index.js
packages/site/src/utils/hooks.js
yarn.lock

refactor: osn common for duplicated hooks

---

packages/site/src/components/Tooltip/index.js
packages/site/src/pages/Bounties/NewBountyButton.js
packages/site/src/pages/BountyDetail/NewChildBountyButton.js
packages/site/src/pages/Proposals/NewProposalButton.js
packages/site/src/pages/Tips/NewTipButton.js

hotfix: new button tooltip content assert

---

packages/site/src/components/_CountDown/CountDown.js
packages/site/src/pages/BountyDetail/ClaimButtonBase.js
packages/site/src/pages/TipDetail/Actions/CloseButton.js
packages/site/src/pages/TipDetail/Actions/EndorseButton.js
packages/site/src/pages/TipDetail/Actions/RetractButton.js
packages/site/src/pages/Tips/EndorseTipsButton.js
packages/site/src/pages/Tips/EndorseTipsModal/index.js

hotfix: tooltip content assert 2

---

packages/site/src/pages/Referenda/Summary.js
packages/site/src/utils/math.js

feat: add all active referenda count

---

packages/site/src/pages/Referenda/Summary.js
packages/site/src/utils/math.js

fix: all referenda count maybe undefined

---

packages/site/src/components/Charts/globalConfig.js
packages/site/src/components/CustomPolarArea.js
packages/site/src/constants/index.js
packages/site/src/pages/Overview/ChartCard.js
packages/site/src/pages/Overview/CustomLabel.js
packages/site/src/pages/Overview/DoughnutCard.js
packages/site/src/pages/Overview/Income.js
packages/site/src/pages/Overview/OpenGovSpend.js
packages/site/src/pages/Overview/Output.js
packages/site/src/pages/Overview/index.js
packages/site/src/styles/tailwindcss.js

feat: spend, income, output, opengov

---

packages/server/config/config.example.js
packages/server/config/index.js
packages/server/src/mongo-price/index.js
packages/server/src/websocket/overview.js

* Add to be awarded
* Add fiatValue
* Add open gov count

Update overview data according to new design

---

packages/site/src/components/CustomPolarArea.js
packages/site/src/utils/math.js

fix: polar area active size

---

packages/site/src/pages/Overview/OpenGovSpend.js

fix: opengov spend polar area hover

---

packages/site/src/App/components.js
packages/site/src/components/Table.js
packages/site/src/components/TimelineCommentWrapper.js
packages/site/src/components/User/Username.js
packages/site/src/components/User/index.js
packages/site/src/pages/Overview/Summary.js
packages/site/src/pages/Overview/index.js
packages/site/src/pages/Transfers/TransfersTable.js

fix: ui #1208

---

site/src/components/Tooltip/index.jsx

fix: user councilor heatmap tooltip position, #1320

---

site/src/components/ProjectProposals.jsx
site/src/components/Table.jsx
site/src/components/ValueDisplay.jsx
site/src/pages/Overview/TopBeneficiariesTable/index.jsx
site/src/pages/Overview/polkadot/index.jsx
site/src/pages/Overview/topFundedProjectsTable/index.jsx
site/src/pages/Projects/NameCell.jsx

treasury overview table lists #1426

---

site/src/components/overview/TreasuryRequestingMessage.jsx
site/src/constants/statemint.js
site/src/hooks/overview/useFiatPriceSnapshot.js
site/src/hooks/overview/useTreasuryRequestingData.js
site/src/pages/Overview/polkadot/totalTreasury.jsx

* feat: create TreasuryRequestingMessage component to show requesting and confirming treasury values
* feat: implement useTreasuryRequestingData hook for fetching treasury data
* feat: add useFiatPriceSnapshot hook for real-time price data
* feat: update totalTreasury page to include TreasuryRequestingMessage component

Add treasury requesting message on overview page, #1551
